name: release

on:
  pull_request:
    branches: [ release ]
  push:
    branches: [ release ]

permissions:
  statuses: write
  contents: read

jobs:
  build-linux:
    name: X11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive --depth 1
      - name: Install dependencies
        run: sudo apt update && sudo apt install xorg-dev

      - name: Test zipped release
        run: script/release.sh
      - name: Move and unzip release
        run: mkdir test_release_zip && mv HW3.zip test_release_zip/HW3.zip && cd test_release_zip && unzip HW3.zip

      - name: Configure release
        run: cmake -S ${{github.workspace}}/test_release_zip -B ${{github.workspace}}/build_rel -DCMAKE_BUILD_TYPE=Release
      - name: Build release
        run: cmake --build ${{github.workspace}}/build_rel --config Release --parallel

      - name: Configure debug
        run: cmake -S ${{github.workspace}}/test_release_zip -B ${{github.workspace}}/build_dbg -DCMAKE_BUILD_TYPE=Debug
      - name: Build debug
        run: cmake --build ${{github.workspace}}/build_dbg --config Debug --parallel


  build-macos:
    name: Cocoa
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive --depth 1

      - name: Test zipped release
        run: script/release.sh
      - name: Move and unzip release
        run: mkdir test_release_zip && mv HW3.zip test_release_zip/HW3.zip && cd test_release_zip && unzip HW3.zip

      - name: Configure release
        run: cmake -S ${{github.workspace}}/test_release_zip -B ${{github.workspace}}/build_rel -DCMAKE_BUILD_TYPE=Release
      - name: Build release
        run: cmake --build ${{github.workspace}}/build_rel --config Release --parallel

      - name: Configure debug
        run: cmake -S ${{github.workspace}}/test_release_zip -B ${{github.workspace}}/build_dbg -DCMAKE_BUILD_TYPE=Debug
      - name: Build debug
        run: cmake --build ${{github.workspace}}/build_dbg --config Debug --parallel

  build-windows-vs2019:
    name: Win32
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive --depth 1

      - name: Configure release
        run: cmake -B ${{github.workspace}}/build_rel -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release
      - name: Build release
        run: cmake --build ${{github.workspace}}/build_rel --config Release --parallel

      - name: Configure debug
        run: cmake -B ${{github.workspace}}/build_dbg -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug
      - name: Build debug
        run: cmake --build ${{github.workspace}}/build_dbg --config Debug --parallel
